server:
  port:  ${PORT:8017}
spring:
  datasource:
    password: ${SENHA_POSTGRE:5432}
    url: ${URL_POSTGRE:jdbc:postgresql://localhost:5432/db-postgres}
    username: ${USUARIO_POSTGRE:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
        ddl-auto: update